# Generated by Django 2.2.5 on 2019-09-23 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketuser',
            name='bio',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='marketuser',
            name='phoneNumber',
            field=models.CharField(default=0, max_length=12),
        ),
    ]
