# Generated by Django 2.2.5 on 2019-10-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190923_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketuser',
            name='unreadMessages',
            field=models.IntegerField(default=0),
        ),
    ]
