# Generated by Django 2.2.6 on 2019-11-19 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_marketuser_unreadmessages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketuser',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='marketuser',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
