# Generated by Django 2.2.5 on 2019-09-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('isbn', models.CharField(help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>', max_length=13, primary_key=True, serialize=False, verbose_name='ISBN')),
                ('publisher', models.CharField(max_length=50, null=True, verbose_name='Publisher')),
                ('published_date', models.DateField()),
                ('author', models.ManyToManyField(null=True, to='market.Author')),
            ],
        ),
    ]
