# Generated by Django 2.2.5 on 2019-09-23 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False)),
                ('condition', models.CharField(blank=True, choices=[('N', 'New'), ('LN', 'Like New'), ('VG', 'Very Good'), ('G', 'Good'), ('F', 'Fair'), ('P', 'Poor')], default='G', help_text='Book condition', max_length=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('comment', models.TextField(max_length=200)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.Book')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
