# Generated by Django 2.2.5 on 2019-09-23 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_auto_20190923_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrequest',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.Transaction'),
        ),
        migrations.AddField(
            model_name='listing',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.Transaction'),
        ),
    ]
