# Generated by Django 2.2.5 on 2019-09-23 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_auto_20190923_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Published Date'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Publisher'),
        ),
        migrations.AlterField(
            model_name='bookrequest',
            name='comment',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='bookrequest',
            name='desired_condition',
            field=models.CharField(choices=[('N', 'New'), ('LN', 'Like New'), ('VG', 'Very Good'), ('G', 'Good'), ('F', 'Fair'), ('P', 'Poor')], default='G', help_text='Book condition', max_length=2),
        ),
        migrations.AlterField(
            model_name='listing',
            name='comment',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='listing',
            name='condition',
            field=models.CharField(choices=[('N', 'New'), ('LN', 'Like New'), ('VG', 'Very Good'), ('G', 'Good'), ('F', 'Fair'), ('P', 'Poor')], default='G', help_text='Book condition', max_length=2),
        ),
    ]
