# Generated by Django 2.2.5 on 2019-10-28 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_usermessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='listing_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.Listing'),
        ),
        migrations.AddField(
            model_name='usermessage',
            name='parent_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent', to='market.UserMessage'),
        ),
        migrations.AddField(
            model_name='usermessage',
            name='request_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.BookRequest'),
        ),
    ]
