# Generated by Django 2.2.5 on 2019-10-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_auto_20191028_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='read_flag',
            field=models.BooleanField(default=False),
        ),
    ]
