# Generated by Django 2.2.5 on 2019-10-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_usermessage_read_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date_closed',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
