# Generated by Django 2.2.6 on 2019-11-19 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0014_auto_20191111_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrequest',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction', to='market.Transaction'),
        ),
    ]
